### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by tcagkansokmen** [Paraboly/react-native-card#11]
I can see it inside node_modules.

But it returns;

Unable to resolve "react-native-androw" from "node_modules/@paraboly/react-native-card/build/dist/components/Card/Card.js"

error.

what could be the problem?

**Comment by tcagkansokmen** [comment]
im using expo. can It get it caused?

it says;
@paraboly/react-native-card@1.0.0 requires a peer of react-native-vector-icons@>= 7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @paraboly/react-native-card@1.0.0 requires a peer of react-native-dynamic-vector-icons@>= 1.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN @paraboly/react-native-card@1.0.0 requires a peer of @freakycoder/react-native-bounceable@>= 0.2.4 but none is installed. You must install peer dependencies yourself.

but i got those on my package.json

**Comment by kuraydev** [comment]
Hello @tcagkansokmen,
Yes, it is because of using the expo. I can create an expo version and remove the `react-native-androw` dependency tomorrow. I will inform you as soon as it is ready :)

**Comment by kuraydev** [comment]
Hello @tcagkansokmen,
Expo version is here.
Please check the [Expo Documentation](https://github.com/Paraboly/react-native-card#expo-version)
