### ISSUE TITLE
Dynamic Height for Card component

### ISSUE THREAD

**Issue by FrancoMuniz** [Paraboly/react-native-card#6]
I'd really appreciate dynamic height being implemented on the Card component!

It's implemented on the "SimpleCard" but not in the "Card" one. 
The idea is basically adjusting the height of the card depending on the size of the content inside.

Thanks!

**Comment by kuraydev** [comment]
Hey again Franco, 
Really sorry it's been a tough week. I will make it ASAP :)

**Comment by kuraydev** [comment]
Hey again @FrancoMuniz,
I've done the dynamic height for the `Card` one :) If you do not want the `dynamic height` you can use the new prop: `textContainerNumberOfLines` :) Thank you for the enhancement request. Waiting for more.

Please check it out: 
## [Release: 0.3.0 🎊🎉🥳](https://github.com/Paraboly/react-native-card/releases/tag/0.3.0)
