### ISSUE TITLE
How to use a card with an empty icon? | Icons are way off their place

### ISSUE THREAD

**Issue by dlogvin** [Paraboly/react-native-card#8]
Hey! I found that color area super cool without an icon, but I'm not sure how to use it without an icon and getting a warning in the console.

Plus, I'm not sure why, but the icon is way off the center, don't know how to fix that either.

**Comment by kuraydev** [comment]
Hello, 
That's a great idea, let me try it first. I will inform you asap :)

**Comment by kuraydev** [comment]
Hello again @danslabs,
If you set these props like this: 
```
iconName=""
iconType=""
```
It will handle it without any problem and it does not show any icon. Also keep the mind that, if you want to use it with colored area, you need to set `textContainerNumberOfLines={3}`
Otherwise, colored area has a design glitch.

**Comment by dlogvin** [comment]
Great! Thank you 🙌🏻

**Comment by kuraydev** [comment]
> Great! Thank you 🙌🏻

If you have any other issue or have an idea, please feel free to share :)

**Comment by dlogvin** [comment]
> > Great! Thank you 🙌🏻
> 
> If you have any other issue or have an idea, please feel free to share :)

This has nothing to do with this thing, but I found in your repos the following one: https://github.com/WrathChaos/react-native-header-view 

In the screenshots you have GORGEOUS cards, do you mind if you tell me how to make them or where to find those? They would really fit an app I'm working on right now, thank you in advance!

**Comment by kuraydev** [comment]
@danslabs I made them :) I can share with you.

**Comment by kuraydev** [comment]
Hey again @danslabs,
Here is the gorgeous card library :)
https://github.com/WrathChaos/react-native-imaged-carousel-card
If you want something else, please open another issue :) I'm open for new ideas.

**Comment by dlogvin** [comment]
Thank you VERY VERY much!!! you're the best!!!
